// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Data;

#nullable disable

namespace TodoApp.Data.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260716215710_SupportMessageTable")]
    partial class SupportMessageTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TodoApp.Models.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TodoApp.Models.Data.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the comment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Content of the comment");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Timestamp when the comment was created");

                    b.Property<Guid>("TodoId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier for the todo to which the comment belongs");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Timestamp when the comment was last updated");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TodoApp.Models.Data.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Unique identifier for the group");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Timestamp when the group was created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name of the group");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Timestamp when the group was last updated, Nullable");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Identifier of the user who owns the group");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67938441-4f26-429a-a328-828208f6f0e6"),
                            CreatedOn = new DateTime(2026, 5, 22, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Work Tasks",
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        },
                        new
                        {
                            Id = new Guid("eb68a07e-7fc9-40e8-bdd4-ce5cd056fb51"),
                            CreatedOn = new DateTime(2026, 5, 21, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Name = "University",
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        },
                        new
                        {
                            Id = new Guid("9ee30a53-b22e-40af-9171-077da6d5d34a"),
                            CreatedOn = new DateTime(2026, 5, 20, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming",
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        },
                        new
                        {
                            Id = new Guid("b4c7c90c-2094-4b50-b3a0-3b123a1583f6"),
                            CreatedOn = new DateTime(2026, 5, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Personal",
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        },
                        new
                        {
                            Id = new Guid("a1a1ab13-d1bc-4a25-8ba7-ca141db73f85"),
                            CreatedOn = new DateTime(2026, 5, 18, 7, 20, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fitness",
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        });
                });

            modelBuilder.Entity("TodoApp.Models.Data.SupportMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Support message primary key");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Support message description text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Support message description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Support message title");

                    b.Property<Guid?>("TodoEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("TodoEntityId");

                    b.ToTable("SupportMessages");
                });

            modelBuilder.Entity("TodoApp.Models.Data.TodoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Todo entity primary key");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Todo creation date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)")
                        .HasComment("Todo description");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasComment("Todo due date");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)")
                        .HasComment("Todo name");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasComment("Todo priority");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("Todo status");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasComment("Todo last update date, Nullable");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5259ecb1-ea01-4b61-82ac-5a50d5c3d6b1"),
                            CreatedOn = new DateTime(2026, 5, 22, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete the ASP.NET Core API",
                            DueDate = new DateOnly(2026, 5, 30),
                            GroupId = new Guid("a1a1ab13-d1bc-4a25-8ba7-ca141db73f85"),
                            Name = "Finish API",
                            Priority = 0,
                            Status = 0,
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        },
                        new
                        {
                            Id = new Guid("9fc3138f-6c8d-47a8-b7b9-192e5df38c7e"),
                            CreatedOn = new DateTime(2026, 5, 21, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepare for Signals and Systems exam",
                            DueDate = new DateOnly(2026, 6, 5),
                            GroupId = new Guid("a1a1ab13-d1bc-4a25-8ba7-ca141db73f85"),
                            Name = "Study Signals",
                            Priority = 1,
                            Status = 0,
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        },
                        new
                        {
                            Id = new Guid("af8c31f0-a176-427d-916e-8eb9bc1cb1e4"),
                            CreatedOn = new DateTime(2026, 5, 20, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            Description = "Play and stream Battlefield 1",
                            DueDate = new DateOnly(2026, 5, 25),
                            GroupId = new Guid("a1a1ab13-d1bc-4a25-8ba7-ca141db73f85"),
                            Name = "Play Battlefield 1",
                            Priority = 2,
                            Status = 1,
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        },
                        new
                        {
                            Id = new Guid("d35d20fb-d640-4095-90a4-a11a3cd7d608"),
                            CreatedOn = new DateTime(2026, 5, 19, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buy food and drinks",
                            DueDate = new DateOnly(2026, 5, 23),
                            GroupId = new Guid("a1a1ab13-d1bc-4a25-8ba7-ca141db73f85"),
                            Name = "Buy groceries",
                            Priority = 1,
                            Status = 0,
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        },
                        new
                        {
                            Id = new Guid("142279f9-cc2c-4766-8a0e-c801174b4fdf"),
                            CreatedOn = new DateTime(2026, 5, 18, 7, 20, 0, 0, DateTimeKind.Unspecified),
                            Description = "Complete cardio and strength training",
                            DueDate = new DateOnly(2026, 5, 24),
                            GroupId = new Guid("b4c7c90c-2094-4b50-b3a0-3b123a1583f6"),
                            Name = "Morning workout",
                            Priority = 0,
                            Status = 0,
                            UserId = new Guid("07420943-635f-4cd8-8850-e0ce781094f2")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TodoApp.Models.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TodoApp.Models.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoApp.Models.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TodoApp.Models.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoApp.Models.Data.Comment", b =>
                {
                    b.HasOne("TodoApp.Models.Data.TodoEntity", "TodoEntity")
                        .WithMany("Comments")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoEntity");
                });

            modelBuilder.Entity("TodoApp.Models.Data.Group", b =>
                {
                    b.HasOne("TodoApp.Models.Data.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoApp.Models.Data.SupportMessage", b =>
                {
                    b.HasOne("TodoApp.Models.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoApp.Models.Data.TodoEntity", null)
                        .WithMany("SupportMessages")
                        .HasForeignKey("TodoEntityId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("TodoApp.Models.Data.TodoEntity", b =>
                {
                    b.HasOne("TodoApp.Models.Data.Group", "Group")
                        .WithMany("Todos")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TodoApp.Models.Data.ApplicationUser", "User")
                        .WithMany("Todos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoApp.Models.Data.ApplicationUser", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("TodoApp.Models.Data.Group", b =>
                {
                    b.Navigation("Todos");
                });

            modelBuilder.Entity("TodoApp.Models.Data.TodoEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("SupportMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
